spring:
  application:
    name: AssetIQ
  threads:
    virtual:
      enabled: ${SPRING_THREADS_VIRTUAL_ENABLED:true}
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:secret@localhost:2702/mydatabase?authSource=admin}

    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Custom MinIO Properties
minio:
  endpoint: ${MINIO_ENDPOINT:http://minio:9000}
  access-key: ${MINIO_ROOT_USER:admin}
  secret-key: ${MINIO_ROOT_PASSWORD:password}
  bucket: ${MINIO_BUCKET:assets}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    mongo:
      enabled: true
    redis:
      enabled: true
