spring:
  application:
    name: AssetIQ
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      uri: mongodb://root:secret@mongodb:27017/mydatabase?authSource=admin
    redis:
      host: redis
      port: 6379
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Custom MinIO Properties
minio:
  endpoint: http://minio:9000
  access-key: admin
  secret-key: password
  bucket: assets